Repository ericberglund117/Rancid-Tomatillos, pull requests merged in 2020-10, with the labels that each got.

#17 Eb sprint 1 movies
  src/Api.js
  src/App.js
Labels: API, enhancement

#18 Mw base styling
  src/App.css
  src/App.js
  src/Movies.css
  src/Movies.js
  src/images/film-reel.png
  src/images/tomatillo.png
Labels: API, SASS

#21 Eb sprint 2 login
  package-lock.json
  package.json
  src/App.js
  src/index.js
  src/login/Login.css
  src/login/Login.js
  src/movies/Movies.css
  src/movies/Movies.js
Labels: API, Error handle, Login, enhancement

#24 started the file move for movies
  src/App.js
  src/movies/Movies.js
Labels: bug

#25 Movie testing
  package-lock.json
  package.json
  src/Api.js
  src/App.js
  src/App.test.js
  src/apiCalls.js
  src/index.js
  src/movies/Movies.css
  src/movies/Movies.js
  src/movies/Movies.test.js
Labels: API, documentation, testing

#26 Single movie
  src/App.js
  src/apiCalls.js
  src/movies/Movies.js
  src/movies/Movies.test.js
  src/single-movie/SingleMovie.css
  src/single-movie/SingleMovie.js
  src/single-movie/SingleMovie.test.js
Labels: API, bug

#29 Eb router
  src/App.js
  src/movies/Movies.js
  src/movies/Movies.test.js
  src/single-movie/SingleMovie.js
Labels: Logout, Router

#31 Mw testing login
  src/apiCalls.js
  src/login/Login.js
  src/login/Login.test.js
  src/movies/Movies.js
  src/movies/Movies.test.js
  src/single-movie/SingleMovie.js
  src/single-movie/SingleMovie.test.js
Labels: testing

#33 Eb delete ratings
  src/App.js
  src/apiCalls.js
  src/user-ratings/UserRatings.js
Labels: API, enhancement

#35 Add the prop types
  package.json
  src/login/Login.js
  src/movies/Movies.js
  src/movies/Movies.test.js
  src/single-movie/SingleMovie.js
  src/user-ratings/UserRatings.js
Labels: testing

#37 Testing Login and Movies
  package-lock.json
  package.json
  src/Test-utils.js
  src/apiCalls.js
  src/login/Login.js
  src/login/Login.test.js
  src/movies/Movies.js
  src/movies/Movies.test.js
  src/single-movie/SingleMovie.test.js
  src/testUtilsFiles.js
Labels: testing

#42 Eb code cleanup
  src/App.js
  src/App.test.js
  src/apiCalls.js
  src/login/Login.js
  src/login/Login.test.js
  src/movies/Movies.css
  src/movies/Movies.js
  src/movies/Movies.test.js
  src/single-movie/SingleMovie.js
  src/single-movie/SingleMovie.test.js
  src/user-ratings/UserRatings.js
  src/user-ratings/UserRatings.test.js
Labels: bug, testing

#43 Eb walkthrough
  package-lock.json
  package.json
  src/App.css
  src/App.js
  src/App.test.js
  src/apiCalls.js
  src/login/Login.css
  src/login/Login.js
  src/login/Login.test.js
  src/movies/Movies.js
  src/movies/Movies.test.js
  src/single-movie/SingleMovie.js
  src/single-movie/SingleMovie.test.js
  src/user-ratings/UserRatings.js
Labels: SASS, bug, testing
